spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    # use druid data source
    type: com.alibaba.druid.pool.DruidDataSource

#spring.datasource.url=jdbc:mysql://localhost:3306/blog_system
#spring.datasource.username=root
#spring.datasource.password=123456